version: '3'
services:
  redis:
    restart: always
    image: redis
    container_name: oz-redis
    ports:
      - '6379:6379'
  db:
    image: postgres
    container_name: oz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - '$HOME/docker/volumes/oz-postgres:/var/lib/postgresql/data'
